TRIVIA_TOPICS = {
    "cs": [
        {"question": "What language is based on a snake?", "answer": "Python"},
        {"question": "What language is based on a coffee bean?", "answer": "Java"},
    ],
    "minecraft": [
        {"question": "What rare biome is home to towering mushrooms and Mooshrooms?", "answer": "Mushroom Fields"},
        {"question": "What block can be used to brew potions?", "answer": "Brewing Stand"},
        {"question": "Which mob drops Blaze Rods when defeated?", "answer": "Blaze"},
        {"question": "What enchantment allows a player to walk on water by turning it into ice?", "answer": "Frost Walker"},
        {"question": "What material is required to craft a Netherite Ingot?", "answer": "Ancient Debris"},
        {"question": "What is the maximum number of levels a beacon can have?", "answer": "4"},
        {"question": "Which block can be used to transport redstone signals vertically?", "answer": "Observer"},
        {"question": "Which mob attacks in a group and can fly through walls?", "answer": "Phantom"},
        {"question": "What is the name of the structure where you can find a Woodland Mansion?", "answer": "Dark Forest"},
        {"question": "What block is immune to Ghast fireballs?", "answer": "Cobblestone"},
        {"question": "What is the maximum enchantment level for Sharpness in survival?", "answer": "5"},
        {"question": "What is the main ingredient in a potion of fire resistance?", "answer": "Magma Cream"},
        {"question": "What tool is required to mine diamonds?", "answer": "Iron Pickaxe"},
        {"question": "What is the name of the dimension filled with Endermen and an obsidian platform?", "answer": "The End"},
        {"question": "What enchantment allows bows to shoot infinite arrows?", "answer": "Infinity"},
        {"question": "What is the maximum number of items a single stack can hold for most items?", "answer": "64"},
        {"question": "What enchantment increases mining speed underwater?", "answer": "Aqua Affinity"},
        {"question": "Which mob can drop a totem of undying?", "answer": "Evoker"},
        {"question": "What is the maximum level for the Fortune enchantment?", "answer": "3"},
        {"question": "What block can be used to attract lightning?", "answer": "Lightning Rod"},
        {"question": "What is the name of the boss mob found in an underwater temple?", "answer": "Elder Guardian"},
        {"question": "Which block allows you to smelt ores twice as fast?", "answer": "Blast Furnace"},
        {"question": "Which item allows Elytra to be repaired?", "answer": "Phantom Membrane"},
        {"question": "What biome is known for its greenish-blue grass and trees?", "answer": "Swamp"},
        {"question": "What is the primary use of Lapis Lazuli?", "answer": "Enchanting items"},
        {"question": "Which mob can drop a Saddle when defeated?", "answer": "Strider"},
        {"question": "What is the maximum range of a beacon?", "answer": "50 blocks"},
        {"question": "What block emits a redstone signal based on the fullness of its inventory?", "answer": "Comparator"},
        {"question": "What is the fastest way to travel in the Nether?", "answer": "Ice Boat"},
        {"question": "What tool do you need to mine sponges quickly?", "answer": "Hoe"},
        {"question": "What is the name of the flower that gives a light blue dye?", "answer": "Blue Orchid"},
        {"question": "What block is required to grow Nether Wart?", "answer": "Soul Sand"},
        {"question": "What item is needed to make a Dispenser?", "answer": "Bow"},
        {"question": "What is the block that villagers use as a job site for clerics?", "answer": "Brewing Stand"},
        {"question": "What block is used to enchant items?", "answer": "Enchanting Table"},
        {"question": "What is the function of a Loom?", "answer": "Crafting banners"},
        {"question": "What is the name of the enchantment that increases attack damage to spiders?", "answer": "Bane of Arthropods"},
        {"question": "Which mob can teleport?", "answer": "Enderman"},
        {"question": "What is the rarest naturally occurring ore?", "answer": "Emerald Ore"},
        {"question": "What block is used to create the Wither Boss?", "answer": "Soul Sand"},
        {"question": "What item is needed to craft a Piston?", "answer": "Redstone"},
        {"question": "What is the name of the biome with red and orange sand and terracotta?", "answer": "Badlands"},
        {"question": "Which item is required to respawn the Ender Dragon?", "answer": "End Crystal"},
        {"question": "What is the maximum level for the Looting enchantment?", "answer": "3"},
        {"question": "What block is created when water touches lava in a vertical flow?", "answer": "Obsidian"},
        {"question": "What is the main ingredient in a potion of invisibility?", "answer": "Golden Carrot"},
        {"question": "What is the name of the structure found in the End filled with Shulkers?", "answer": "End City"},
        {"question": "What tool is used to carve pumpkins?", "answer": "Shears"},
        {"question": "Which block can be used to craft red dye?", "answer": "Poppy"},
        {"question": "What item is needed to craft an Enchanting Table?", "answer": "Obsidian"},
        {"question": "What mob is neutral but becomes hostile if you attack it or mine gold?", "answer": "Piglin"},
        {"question": "Which mob is immune to fire damage?", "answer": "Strider"},
        {"question": "What enchantment allows you to breathe underwater for longer?", "answer": "Respiration"},
        {"question": "What is the function of a Stonecutter?", "answer": "Cuts stone into slabs, stairs, or other variants"},
        {"question": "What is the name of the food item that can poison the player?", "answer": "Pufferfish"},
        {"question": "What is the name of the structure that generates in the ocean and contains Elder Guardians?", "answer": "Ocean Monument"},
        {"question": "What is required to craft a shield?", "answer": "Wood and Iron Ingot"},
        {"question": "What block prevents mobs from spawning in its area?", "answer": "Light Block"},
        {"question": "What item can be used to move bees to a new hive?", "answer": "Leash"},
        {"question": "What is the name of the effect that causes hearts to regenerate faster?", "answer": "Regeneration"},
        {"question": "What block is needed to summon the Ender Dragon again?", "answer": "End Crystal"},
        {"question": "What item can be smelted into Green Dye?", "answer": "Cactus"},
        {"question": "Which mob can hold a trident?", "answer": "Drowned"},
        {"question": "What tool is required to mine sponges quickly?", "answer": "Hoe"},
        {"question": "What block is required to grow Nether Wart?", "answer": "Soul Sand"},
        {"question": "What item is needed to make a Dispenser?", "answer": "Bow"},
        {"question": "What block is used to enchant items?", "answer": "Enchanting Table"},
    ],
    "LoL": [
        {"question": "What is the name of the map used for Summoner's Rift?", "answer": "Summoner's Rift"},
        {"question": "Which champion is known as the Nine-Tailed Fox?", "answer": "Ahri"},
        {"question": "What is the maximum level a champion can reach in a match?", "answer": "18"},
        {"question": "Which item grants bonus gold when assisting or killing an enemy?", "answer": "Dark Seal"},
        {"question": "What is the role of champions who typically play in the bottom lane and focus on dealing high damage?", "answer": "ADC"},
        {"question": "Which champion wields a scythe and has abilities focused on harvesting souls?", "answer": "Thresh"},
        {"question": "What is the name of the creature in the jungle that grants a buff to nearby allies upon defeat?", "answer": "Rift Herald"},
        {"question": "What ability allows champions to teleport to any location within a short range?", "answer": "Flash"},
        {"question": "What is the term for killing an enemy without taking any damage?", "answer": "Clean Kill"},
        {"question": "What is the maximum number of dragons a team can kill before achieving the Dragon Soul?", "answer": "4"},
        {"question": "Which champion is associated with the phrase 'Demacia!'?", "answer": "Garen"},
        {"question": "What is the name of the bonus gold structure located in each lane?", "answer": "Turret Plates"},
        {"question": "Which item provides a spell shield to block one enemy ability?", "answer": "Banshee's Veil"},
        {"question": "What is the term for killing an enemy while also dying in the process?", "answer": "Trade Kill"},
        {"question": "Which champion transforms between human and spider forms?", "answer": "Elise"},
        {"question": "What is the name of the buff granted by defeating Baron Nashor?", "answer": "Baron Nashor"},
        {"question": "Which summoner spell heals the caster and nearby allies?", "answer": "Heal"},
        {"question": "Which champion is known for their wind wall ability?", "answer": "Yasuo"},
        {"question": "What is the term for a group of champions and minions pushing together down a lane?", "answer": "Wave"},
        {"question": "Which jungle camp contains two golems that split into smaller ones?", "answer": "Krugs"},
        {"question": "What is the maximum cooldown reduction that can be achieved?", "answer": "40%"},
        {"question": "Which champion is a yordle with a boomerang as a weapon?", "answer": "Gnar"},
        {"question": "What is the term for buying items during a match to enhance stats?", "answer": "Itemization"},
        {"question": "What is the role of champions who primarily focus on healing and shielding teammates?", "answer": "Support"},
        {"question": "Which champion is nicknamed the 'Unforgiven'?", "answer": "Yasuo"},
        {"question": "What is the term for eliminating the entire enemy team?", "answer": "Ace"},
        {"question": "Which champion is known for summoning turrets?", "answer": "Heimerdinger"},
        {"question": "What is the name of the ability that allows champions to return to the fountain?", "answer": "Recall"},
        {"question": "What is the name of the item that increases attack speed and critical strike chance?", "answer": "Infinity Edge"},
        {"question": "Which champion is a blind monk with a powerful kick?", "answer": "Lee Sin"},
        {"question": "What is the term for securing objectives and applying pressure in multiple lanes?", "answer": "Macro Play"},
        {"question": "What is the name of the passive gold income item for supports?", "answer": "Spellthief's Edge"},
        {"question": "Which champion is a shapeshifter with an ability to mimic other champions?", "answer": "Neeko"},
        {"question": "What is the term for gaining vision over an area using wards?", "answer": "Warding"},
        {"question": "Which champion is known for their large shield and crescent moon abilities?", "answer": "Diana"},
        {"question": "What is the name of the summoner spell that reduces healing and deals true damage?", "answer": "Ignite"},
        {"question": "Which champion has a hook ability called Death Sentence?", "answer": "Thresh"},
        {"question": "What is the term for being out of mana and unable to use abilities?", "answer": "OOM"},
        {"question": "Which champion rides a boar and charges into battle?", "answer": "Sejuani"},
        {"question": "What is the term for predicting and dodging enemy abilities?", "answer": "Outplay"},
        {"question": "Which champion is known for their spinning axe ability?", "answer": "Draven"},
        {"question": "What is the name of the buff granted by defeating the Elder Dragon?", "answer": "Elder Dragon Buff"},
        {"question": "Which champion is a time-traveling inventor?", "answer": "Ekko"},
        {"question": "What is the name of the consumable item that grants vision for a short time?", "answer": "Control Ward"},
        {"question": "Which champion is a frost archer with a global ultimate?", "answer": "Ashe"},
        {"question": "What is the term for applying constant pressure in one lane to force enemies to respond?", "answer": "Split Pushing"},
        {"question": "What is the term for intentionally losing a match to lower rank?", "answer": "Trolling"},
        {"question": "Which champion is known for their ability to charm enemies?", "answer": "Ahri"},
        {"question": "What is the name of the early-game monster that grants a health regeneration buff?", "answer": "Red Brambleback"},
        {"question": "What is the name of the ability that allows a champion to slow and freeze enemies?", "answer": "Glacial Augment"},
        {"question": "What is the term for gaining experience from minions and jungle camps?", "answer": "Farming"},
        {"question": "Which champion is known for their 'Black Shield' ability?", "answer": "Morgana"},
        {"question": "Which item provides bonus health and increases crowd control effects?", "answer": "Dead Man's Plate"},
        {"question": "What is the name of the champion with the ability to turn invisible and create clones?", "answer": "Shaco"}
    ],
    
    "all_topics": [],  # Placeholder; will be populated dynamically if all_topics is selected
}

# Populate "all_topics" with questions from all other topics
for topic, questions in TRIVIA_TOPICS.items():
    if topic != "all_topics":
        TRIVIA_TOPICS["all_topics"].extend(questions)