TRIVIA_TOPICS = {
    "cs": [
        {"question": "What language is based on a snake?", "answer": "Python"},
        {"question": "What language is based on a coffee bean?", "answer": "Java"},
    ],
    "minecraft": [
        {"question": "What rare biome is home to towering mushrooms and Mooshrooms?", "answer": "Mushroom Fields"},
        {"question": "What block can be used to brew potions?", "answer": "Brewing Stand"},
        {"question": "Which mob drops Blaze Rods when defeated?", "answer": "Blaze"},
        {"question": "What enchantment allows a player to walk on water by turning it into ice?", "answer": "Frost Walker"},
        {"question": "What material is required to craft a Netherite Ingot?", "answer": "Ancient Debris"},
        {"question": "What is the maximum number of levels a beacon can have?", "answer": "4"},
        {"question": "Which block can be used to transport redstone signals vertically?", "answer": "Observer"},
        {"question": "Which mob attacks in a group and can fly through walls?", "answer": "Phantom"},
        {"question": "What is the name of the structure where you can find a Woodland Mansion?", "answer": "Dark Forest"},
        {"question": "What block is immune to Ghast fireballs?", "answer": "Cobblestone"},
        {"question": "What is the maximum enchantment level for Sharpness in survival?", "answer": "5"},
        {"question": "What is the main ingredient in a potion of fire resistance?", "answer": "Magma Cream"},
        {"question": "What tool is required to mine diamonds?", "answer": "Iron Pickaxe"},
        {"question": "What is the name of the dimension filled with Endermen and an obsidian platform?", "answer": "The End"},
        {"question": "What enchantment allows bows to shoot infinite arrows?", "answer": "Infinity"},
        {"question": "What is the maximum number of items a single stack can hold for most items?", "answer": "64"},
        {"question": "What enchantment increases mining speed underwater?", "answer": "Aqua Affinity"},
        {"question": "Which mob can drop a totem of undying?", "answer": "Evoker"},
        {"question": "What is the maximum level for the Fortune enchantment?", "answer": "3"},
        {"question": "What block can be used to attract lightning?", "answer": "Lightning Rod"},
        {"question": "What is the name of the boss mob found in an underwater temple?", "answer": "Elder Guardian"},
        {"question": "Which block allows you to smelt ores twice as fast?", "answer": "Blast Furnace"},
        {"question": "Which item allows Elytra to be repaired?", "answer": "Phantom Membrane"},
        {"question": "What biome is known for its greenish-blue grass and trees?", "answer": "Swamp"},
        {"question": "What is the primary use of Lapis Lazuli?", "answer": "Enchanting items"},
        {"question": "What block generates snow when a Snow Golem walks on it?", "answer": "Snow Layer"},
        {"question": "Which mob can drop a Saddle when defeated?", "answer": "Strider"},
        {"question": "What is the maximum range of a beacon?", "answer": "50 blocks"},
        {"question": "What block emits a redstone signal based on the fullness of its inventory?", "answer": "Comparator"},
        {"question": "What is the fastest way to travel in the Nether?", "answer": "Ice Boat"},
        {"question": "What tool do you need to mine sponges quickly?", "answer": "Hoe"},
        {"question": "What is the name of the flower that gives a light blue dye?", "answer": "Blue Orchid"},
        {"question": "What block is required to grow Nether Wart?", "answer": "Soul Sand"},
        {"question": "What item is needed to make a Dispenser?", "answer": "Bow"},
        {"question": "What is the block that villagers use as a job site for clerics?", "answer": "Brewing Stand"},
        {"question": "What block is used to enchant items?", "answer": "Enchanting Table"},
        {"question": "What is the function of a Loom?", "answer": "Crafting banners"},
        {"question": "What is the name of the enchantment that increases attack damage to spiders?", "answer": "Bane of Arthropods"},
        {"question": "Which mob can teleport?", "answer": "Enderman"},
        {"question": "What is the rarest naturally occurring ore?", "answer": "Emerald Ore"},
        {"question": "What block is used to create the Wither Boss?", "answer": "Soul Sand"},
        {"question": "What item is needed to craft a Piston?", "answer": "Redstone"},
        {"question": "What is the name of the biome with red and orange sand and terracotta?", "answer": "Badlands"},
        {"question": "Which item is required to respawn the Ender Dragon?", "answer": "End Crystal"},
        {"question": "What is the maximum level for the Looting enchantment?", "answer": "3"},
        {"question": "What block is created when water touches lava in a vertical flow?", "answer": "Obsidian"},
        {"question": "What is the main ingredient in a potion of invisibility?", "answer": "Golden Carrot"},
        {"question": "What is the name of the structure found in the End filled with Shulkers?", "answer": "End City"},
        {"question": "What tool is used to carve pumpkins?", "answer": "Shears"},
        {"question": "Which block can be used to craft red dye?", "answer": "Poppy"},
        {"question": "What item is needed to craft an Enchanting Table?", "answer": "Obsidian"},
        {"question": "What mob is neutral but becomes hostile if you attack it or mine gold?", "answer": "Piglin"},
        {"question": "Which mob is immune to fire damage?", "answer": "Strider"},
        {"question": "What enchantment allows you to breathe underwater for longer?", "answer": "Respiration"},
        {"question": "What is the function of a Stonecutter?", "answer": "Cuts stone into slabs, stairs, or other variants"},
        {"question": "What is the name of the food item that can poison the player?", "answer": "Pufferfish"},
        {"question": "What is the name of the structure that generates in the ocean and contains Elder Guardians?", "answer": "Ocean Monument"},
        {"question": "What is required to craft a shield?", "answer": "Wood and Iron Ingot"},
        {"question": "What block prevents mobs from spawning in its area?", "answer": "Light Block"},
        {"question": "What item can be used to move bees to a new hive?", "answer": "Leash"},
        {"question": "What is the name of the effect that causes hearts to regenerate faster?", "answer": "Regeneration"},
        {"question": "What block is needed to summon the Ender Dragon again?", "answer": "End Crystal"},
        {"question": "What item can be smelted into Green Dye?", "answer": "Cactus"},
        {"question": "Which mob can hold a trident?", "answer": "Drowned"},
        {"question": "What tool is required to mine sponges quickly?", "answer": "Hoe"},
        {"question": "What block is required to grow Nether Wart?", "answer": "Soul Sand"},
        {"question": "What item is needed to make a Dispenser?", "answer": "Bow"},
        {"question": "What block is used to enchant items?", "answer": "Enchanting Table"},
    ],
    
    "all_topics": [],  # Placeholder; will be populated dynamically if all_topics is selected
}

# Populate "all_topics" with questions from all other topics
for topic, questions in TRIVIA_TOPICS.items():
    if topic != "all_topics":
        TRIVIA_TOPICS["all_topics"].extend(questions)